### ISSUE TITLE
Add RGBA capability to color chooser

### ISSUE THREAD

**Issue by sandrobilbeisi** [evertiro/historical-redux2#153]
We should add a RGBA-capable color chooser 

Basically every color picker would be RGBA
RGB values would be programmatically derived by stripping the alpha

generated CSS would look like:

``` CSS
div {
   background: rgb(200, 54, 54); /* The Fallback */
   background: rgba(200, 54, 54, 0.5); 
}
```

RGBA works with FireFox 3+, Safari 3+, Opera 10 +, Chrome, Explorer 9+, Mobile Safari, Android Browser, BlackBerry Storm, Samsung @TV, GoogleTV

Alternatively, every RGBA color picker would have a subordinate older color chooser to provide the fallback color

The current color picker in WordPress 3.5 -- 3.6 is Iris by Automattic http://automattic.github.io/Iris/

I suggest replacing it with "jQuery UI Color Picker Widget" http://lindekleiv.bitbucket.org/colorpicker/# it uses almost the same exact API

or even : rgbaColorPicker : http://fatfolderdesign.com/ex/rgbaColorPicker/
https://github.com/pgooch/rgbaColorPicker

RGBA tips: http://css-tricks.com/rgba-browser-support/
