### ISSUE TITLE
Help using Google web fonts

### ISSUE THREAD

**Issue by hectorgarrofe** [evertiro/historical-redux2#81]
Hello,

I'm using the Google web font field to let my users select a font.

For example, a user chooses the font "Yanone Kaffeesatz 700", and the value returned by the field is: ''Yanone+Kaffeesatz:700".

I load the web font adding:

<code>link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=<?php echo $options['google_webfonts']; ?>"</code>

This is working and the font is loading correctly, but... How can I use font in my theme now!?

I made a deep research and I can't figured out how to do it.

Thanks in advance.

**Comment by djevrek** [comment]
``` html
<style>
body {
    font-style: "Yanone Kaffeesatz";
    font-weight:bold;
}
</style>
```

**Comment by hectorgarrofe** [comment]
I don't undestand.

If I use:

``` css
<style>
body {
    font-style: "Yanone Kaffeesatz";
    font-weight:bold;
}
</style>
```

I'm limiting the user to one font. What I want to achieve is that if a user chooses a font, then that font can be used in the style.

I can't harcode font-style: "Yanone Kaffeesatz"; Why let the user choose a font if I force to use one in the style? It has to work dynamically.

Something like:

``` css
font-family: '<?php echo $font_name; ?>', serif;
```

I don't know if I explain well, what I say is very simple, as it's supposed to and does work in other themes.

Thanks again.

**Comment by psaikali** [comment]
You have to use regex on $options['google_webfonts'] to remove the ':700' and replace the '+' with a space. 
I can give you the direction, but not the solution ;) I still have to learn how to write regular expression.

**Comment by poblabs** [comment]
I haven't used this feature yet so I may be wrong, but I'll give a go at this. You may already know this, but just in case. 

First you'll need to open your `themes-options.php` (or options.php if you didn't make a copy) and find what you set for `$args['opt_name']`. For this example, we'll say that it's set as `$args['opt_name'] = 'Redux';`

You'll also want to find the name of the Google Font ID you used for that field. For example:

``` php
'id' => 'google_webfonts_demo',
'type' => 'google_webfonts',
```

Then in your `header.php` (or `functions.php` depending on what you're doing) you'll want something like:

``` php
$redux_options = get_option('Redux');
```

As well as this:

``` css
<style>
body {
   font-style: "<?php echo $redux_options['google_webfonts_demo']; ?>";
   font-weight:bold;
}
</style>
```

Like I said, it may not be exact since I haven't used this yet, but hopefully this is enough to get you started.

**Comment by hectorgarrofe** [comment]
@psaikali That's what I did. And works... but I don't think this is the best solution.

I'll share my code when I get it tested.

**Comment by hectorgarrofe** [comment]
@drsprite

All your steps are correct except the last one:

``` css
<style>
body {
   font-style: "<?php echo $redux_options['google_webfonts_demo']; ?>";
   font-weight:bold;
}
</style>
```

This returns something like this:

``` css
<style>
body {
   font-style: "Yanone+Kaffeesatz:700";
   font-weight:bold;
}
</style>
```

And of course, doesn't work.

I found myself a solution, very similar like @psaikali.

I'll share the code when I get it tested.

**Comment by hectorgarrofe** [comment]
As I said,

``` php
$options['font']
```

returns an string like: "Yanone+Kaffeesatz:700".

We can't use this string in the font-family attribute because it's not a valid font-name. So I wrote this code to clean the string and get the font-family name without the (+) characters and the font-weight (:700).

``` php
$font_name = $options['font'];
$font_name = str_replace("+", " ", $font_name);
$font_name = explode(":", $font_name);
$font_name = $font_name[0];
```

Now I can use:

``` css
<style>
body {
   font-family: '<?php echo $font_name; ?>', serif;
}
</style>
```

And get it working.

I also use: https://developers.google.com/webfonts/docs/webfont_loader to load the fonts dinamically like this:

``` javascript
    <script type="text/javascript">
      WebFontConfig = {
        google: { families: [ 'php<?php echo $options['font_name']; ?>', '<?php echo $options['font_name2']; ?>' ] }
      };
      (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
            '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
      })();
    </script>
```

Sure it's not the best solution, but for me, is working.

I think the best solution would be that `$options['font']` returns an array like this:

``` php
Array
(
    [font-family] => font-family: 'Abel', sans-serif;
    [font-name] => Abel
    [css-name] => Abel
    ...
)
```

I think Google doesn't provide data like this in the API, but take a look at this. http://phat-reaction.com/googlefonts.php

I think it can be a good solution.

Thanks!
